batch_size: 1
cache_dir: lightning_logs/multimodal_llama_2025-09-09_14-12-44/cache
features_file: /data/TalkingLatents/logs/2025-07-29/features.npy
freeze_llm: true
freeze_spectral: true
hidden_dim: 512
json_file: /data/TalkingLatents/data/dataset/stellar_descriptions_questions_short.json
learning_rate: 0.0001
llm_model_path: /data/.llama/Llama3.1-8B
lora_config: null
max_epochs: 100
max_seq_length: 128
num_spectral_features: 1
num_workers: 4
random_seed: 42
spectral_config_path: /data/DESA/logs/spec_decode2_2025-02-16/MultiTaskRegressor_spectra__decode_4_complete_config.yaml
spectral_embedding_dim: 2048
spectral_weights_path: /data/DESA/logs/spec_decode2_2025-02-16/MultiTaskRegressor_spectra_decode_4.pth
test_ratio: 0.1
tokenizer_path: /data/.llama/Llama3.1-8B/tokenizer.model
train_ratio: 0.8
use_lora: false
val_ratio: 0.1
warmup_epochs: 2
weight_decay: 0.001
